// Generated by Selenium IDE
const Chrome = require('selenium-webdriver/chrome');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const options = new Chrome.Options();
options.addArguments('headless')
options.addArguments('--remote-debugging-pipe')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://127.0.0.1:8080/")
    await driver.findElement(By.css("button")).click()
    await driver.close()
  })
})
