on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Selenium Tests
    strategy:
      fail-fast: false
      max-parallel: 5
    steps:
    - name: Install dependencies
      run: |
      set -ex
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt install ./google-chrome-stable_current_amd64.deb
  - uses: nanasess/setup-chromedriver@v1
  - run: chromedriver --url-base=/wd/hub &amp;

    - uses: actions/checkout@v3
    - run: npm i
 
    - name: Run end to end tests
      run: npm run e2e-test