on: [push]
 
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Selenium Tests
    steps:
    - uses: actions/checkout@v1
    - run: npm i
 
    - name: Run end to end tests
      run: npm run e2e-test