on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Selenium Tests
    strategy:
      fail-fast: false
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - run: npm i
 
    - name: Run end to end tests
      run: npm run e2e-test